=== gustavomarcelonunez/gbif-chatbot/response_1720786934558_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "offset": {
      "type": "number"
    },
    "limit": {
      "type": "number"
    },
    "endOfRecords": {
      "type": "boolean"
    },
    "count": {
      "type": "number"
    },
    "results": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "installationKey": {
            "type": "string"
          },
          "publishingOrganizationKey": {
            "type": "string"
          },
          "networkKeys": {
            "type": "array",
            "items": {}
          },
          "doi": {
            "type": "string"
          },
          "version": {
            "type": "string"
          },
          "external": {
            "type": "boolean"
          },
          "numConstituents": {
            "type": "number"
          },
          "type": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "language": {
            "type": "string"
          },
          "homepage": {
            "type": "string"
          },
          "citation": {
            "type": "object",
            "properties": {
              "text": {
                "type": "string"
              },
              "citationProvidedBySource": {
                "type": "boolean"
              }
            },
            "required": [
              "text",
              "citationProvidedBySource"
            ]
          },
          "contactsCitation": {
            "type": "array",
            "items": {}
          },
          "lockedForAutoUpdate": {
            "type": "boolean"
          },
          "createdBy": {
            "type": "string"
          },
          "modifiedBy": {
            "type": "string"
          },
          "created": {
            "type": "string"
          },
          "modified": {
            "type": "string"
          },
          "contacts": {
            "description": "List of person involved in dataset, cam be a CURATOR, METADATA_AUTHOR, ORIGINATOR, CONTENT_PROVIDER,etc",
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "key": {
                  "type": "number"
                },
                "type": {
                  "type": "string"
                },
                "primary": {
                  "type": "boolean"
                },
                "userId": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                },
                "position": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "email": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "phone": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "homepage": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "organization": {
                  "type": "string"
                },
                "address": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "city": {
                  "type": "string"
                },
                "province": {
                  "type": "string"
                },
                "country": {
                  "type": "string"
                },
                "postalCode": {
                  "type": "string"
                },
                "createdBy": {
                  "type": "string"
                },
                "modifiedBy": {
                  "type": "string"
                },
                "created": {
                  "type": "string"
                },
                "modified": {
                  "type": "string"
                }
              },
              "required": [
                "key",
                "type",
                "primary",
                "userId",
                "firstName",
                "lastName",
                "position",
                "email",
                "phone",
                "homepage",
                "organization",
                "address",
                "city",
                "province",
                "country",
                "postalCode",
                "createdBy",
                "modifiedBy",
                "created",
                "modified"
              ]
            }
          },
          "endpoints": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "key": {
                  "type": "number"
                },
                "type": {
                  "type": "string"
                },
                "url": {
                  "type": "string"
                },
                "createdBy": {
                  "type": "string"
                },
                "modifiedBy": {
                  "type": "string"
                },
                "created": {
                  "type": "string"
                },
                "modified": {
                  "type": "string"
                },
                "machineTags": {
                  "type": "array",
                  "items": {}
                }
              },
              "required": [
                "key",
                "type",
                "url",
                "createdBy",
                "modifiedBy",
                "created",
                "modified",
                "machineTags"
              ]
            }
          },
          "machineTags": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "key": {
                  "type": "number"
                },
                "namespace": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                },
                "createdBy": {
                  "type": "string"
                },
                "created": {
                  "type": "string"
                }
              },
              "required": [
                "key",
                "namespace",
                "name",
                "value",
                "createdBy",
                "created"
              ]
            }
          },
          "tags": {
            "type": "array",
            "items": {}
          },
          "identifiers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "key": {
                  "type": "number"
                },
                "type": {
                  "type": "string"
                },
                "identifier": {
                  "type": "string"
                },
                "createdBy": {
                  "type": "string"
                },
                "created": {
                  "type": "string"
                }
              },
              "required": [
                "key",
                "type",
                "identifier",
                "createdBy",
                "created"
              ]
            }
          },
          "comments": {
            "type": "array",
            "items": {}
          },
          "bibliographicCitations": {
            "type": "array",
            "items": {}
          },
          "curatorialUnits": {
            "type": "array",
            "items": {}
          },
          "taxonomicCoverages": {
            "type": "array",
            "items": {}
          },
          "geographicCoverages": {
            "type": "array",
            "items": {}
          },
          "temporalCoverages": {
            "type": "array",
            "items": {}
          },
          "keywordCollections": {
            "type": "array",
            "items": {}
          },
          "countryCoverage": {
            "type": "array",
            "items": {}
          },
          "collections": {
            "type": "array",
            "items": {}
          },
          "dataDescriptions": {
            "type": "array",
            "items": {}
          },
          "maintenanceUpdateFrequency": {
            "type": "string"
          },
          "maintenanceChangeHistory": {
            "type": "array",
            "items": {}
          },
          "license": {
            "type": "string"
          }
        },
        "required": [
          "key",
          "installationKey",
          "publishingOrganizationKey",
          "networkKeys",
          "doi",
          "version",
          "external",
          "numConstituents",
          "type",
          "title",
          "description",
          "language",
          "homepage",
          "citation",
          "contactsCitation",
          "lockedForAutoUpdate",
          "createdBy",
          "modifiedBy",
          "created",
          "modified",
          "contacts",
          "endpoints",
          "machineTags",
          "tags",
          "identifiers",
          "comments",
          "bibliographicCitations",
          "curatorialUnits",
          "taxonomicCoverages",
          "geographicCoverages",
          "temporalCoverages",
          "keywordCollections",
          "countryCoverage",
          "collections",
          "dataDescriptions",
          "maintenanceUpdateFrequency",
          "maintenanceChangeHistory",
          "license"
        ]
      }
    }
  },
  "required": [
    "offset",
    "limit",
    "endOfRecords",
    "count",
    "results"
  ]
}

=== gustavomarcelonunez/gbif-chatbot/response_1720786934558_data.json
{
  "offset": 0,
  "limit": 20,
  "endOfRecords": true,
  "count": 1,
  "results": [
    {
      "key": "19a76d4d-58cf-4d82-aadd-0ae851fc475f",
      "installationKey": "4fd221cd-129c-404f-ab62-fdd2377d12ac",
      "publishingOrganizationKey": "dfd2c300-b2a3-4deb-ad15-00508affc7b5",
      "networkKeys": [],
      "doi": "10.15468/87ndwt",
      "version": "1.2",
      "external": false,
      "numConstituents": 0,
      "type": "OCCURRENCE",
      "title": "Colección de Paleoinvertebrados  del IANIGLA-CCT CONICET Mendoza: IANIGLA-PI",
      "description": "Conjunto de datos perteneciente a la Colección de Paleoinvertebrados del IANIGLA-CCT CONICET Mendoza (Argentina) identificada bajo el acrónimo IANIGLA-PI. El material fósil proviene de la colecta y estudio realizados por investigadores de esta institución y de otros centros de Argentina en el marco de proyectos de investigación en virtud de la ley de “Protección del Patrimonio Arqueológico y Paleontológico”. El dataset incluye 2790 registros fósiles. Los ejemplares pertenecientes al Reino Animalia representan la mayor parte del dataset y suman el 98 % (Phylum Annelida, Arthropoda, Brachiopoda, Chordata, Cnidaria, Hemichordata, Mollusca y Porifera). Se presentan además: un ejemplar del Reino Protoctista (Phylum Granoreticulosa) y cuatro registros del Reino Chlorobionta (Phylum Charophyta), 19 ootecas, y 6 trombolitos. La colección tiene 149 especies, 19 holotipos y 67 paratipos. Todos los ejemplares fueron revisados por especialistas. El 86% de los ejemplares proceden fundamentalmente de secuencias paleozoicas y mesozoicas de las provincias de Mendoza y San Juan (Argentina). La curadora de esta colección es Susana Mariel Devincenzi, Licenciada en Ciencias Geológicas.",
      "language": "spa",
      "homepage": "https://www.ianigla.mendoza-conicet.gob.ar/bases/banco/fotos/index.php?/category/Paleoinvertebrados",
      "citation": {
        "text": "Devincenzi, S M. Colección de Paleoinvertebrados del IANIGLA-CONICET Mendoza: IANIGLA-PI",
        "citationProvidedBySource": false
      },
      "contactsCitation": [],
      "lockedForAutoUpdate": false,
      "createdBy": "dfd2c300-b2a3-4deb-ad15-00508affc7b5",
      "modifiedBy": "crawler.gbif.org",
      "created": "2024-05-03T23:37:25.571+00:00",
      "modified": "2024-05-13T01:43:45.507+00:00",
      "contacts": [
        {
          "key": 5322537,
          "type": "ORIGINATOR",
          "primary": true,
          "userId": [
            "https://orcid.org/0000-0002-4716-1309"
          ],
          "firstName": "Susana Mariel",
          "lastName": "Devincenzi",
          "position": [
            "Curadora Colección"
          ],
          "email": [
            "sdevincenzi@mendoza-conicet.gob.ar"
          ],
          "phone": [
            "+54-261-5244274"
          ],
          "homepage": [
            "https://www.conicet.gov.ar/new_scp/detalle.php?id=40411&datos_academicos=yes&keywords="
          ],
          "organization": "IANIGLA-CCT CONICET Mendoza",
          "address": [
            "Av. Ruiz Leal s/n"
          ],
          "city": "Mendoza",
          "province": "Mendoza",
          "country": "AR",
          "postalCode": "5500",
          "createdBy": "crawler.gbif.org",
          "modifiedBy": "crawler.gbif.org",
          "created": "2024-05-13T01:43:45.467+00:00",
          "modified": "2024-05-13T01:43:45.467+00:00"
        },
        {
          "key": 5322538,
          "type": "METADATA_AUTHOR",
          "primary": true,
          "userId": [
            "https://orcid.org/0000-0002-4716-1309"
          ],
          "firstName": "Susana Mariel",
          "lastName": "Devincenzi",
          "position": [
            "Curadora Colección"
          ],
          "email": [
            "sdevincenzi@mendoza-conicet.gob.ar"
          ],
          "phone": [
            "+54-261-5244274"
          ],
          "homepage": [
            "https://www.conicet.gov.ar/new_scp/detalle.php?id=40411&datos_academicos=yes&keywords="
          ],
          "organization": "IANIGLA-CCT CONICET Mendoza",
          "address": [
            "Av. Ruiz Leal s/n"
          ],
          "city": "Mendoza",
          "province": "Mendoza",
          "country": "AR",
          "postalCode": "5500",
          "createdBy": "crawler.gbif.org",
          "modifiedBy": "crawler.gbif.org",
          "created": "2024-05-13T01:43:45.471+00:00",
          "modified": "2024-05-13T01:43:45.471+00:00"
        },
        {
          "key": 5322539,
          "type": "CURATOR",
          "primary": false,
          "userId": [
            "https://orcid.org/0000-0002-4716-1309"
          ],
          "firstName": "Susana Mariel",
          "lastName": "Devincenzi",
          "position": [
            "Curadora Colección"
          ],
          "email": [
            "sdevincenzi@mendoza-conicet.gob.ar"
          ],
          "phone": [
            "+54-261-5244274"
          ],
          "homepage": [
            "https://www.conicet.gov.ar/new_scp/detalle.php?id=40411&datos_academicos=yes&keywords="
          ],
          "organization": "IANIGLA-CCT CONICET Mendoza",
          "address": [
            "Av. Ruiz Leal s/n"
          ],
          "city": "Mendoza",
          "province": "Mendoza",
          "country": "AR",
          "postalCode": "5500",
          "createdBy": "crawler.gbif.org",
          "modifiedBy": "crawler.gbif.org",
          "created": "2024-05-13T01:43:45.472+00:00",
          "modified": "2024-05-13T01:43:45.472+00:00"
        },
        {
          "key": 5322540,
          "type": "CONTENT_PROVIDER",
          "primary": false,
          "userId": [],
          "firstName": "Osvaldo",
          "lastName": "Bordonaro",
          "position": [
            "Investigador"
          ],
          "email": [
            "osvaldobordonaro@gmail.com"
          ],
          "phone": [],
          "homepage": [],
          "organization": "IANIGLA-CCT CONICET Mendoza",
          "address": [
            "Av. Ruiz Leal s/n"
          ],
          "city": "Mendoza",
          "province": "Mendoza",
          "country": "AR",
          "postalCode": "5500",
          "createdBy": "crawler.gbif.org",
          "modifiedBy": "crawler.gbif.org",
          "created": "2024-05-13T01:43:45.474+00:00",
          "modified": "2024-05-13T01:43:45.474+00:00"
        },
        {
          "key": 5322541,
          "type": "CONTENT_PROVIDER",
          "primary": false,
          "userId": [],
          "firstName": "Javier",
          "lastName": "Echevarría",
          "position": [
            "investigador"
          ],
          "email": [
            "javierechevarria@fcnym.unlp.edu.ar"
          ],
          "phone": [],
          "homepage": [],
          "organization": "Museo de Ciencias Naturales La Plata",
          "address": [],
          "city": "La Plata",
          "province": "Buenos Aires",
          "country": "AR",
          "postalCode": "1900",
          "createdBy": "crawler.gbif.org",
          "modifiedBy": "crawler.gbif.org",
          "created": "2024-05-13T01:43:45.476+00:00",
          "modified": "2024-05-13T01:43:45.476+00:00"
        },
        {
          "key": 5322542,
          "type": "CONTENT_PROVIDER",
          "primary": false,
          "userId": [],
          "firstName": "Maria Belén",
          "lastName": "Lara",
          "position": [
            "Investigadora"
          ],
          "email": [
            "lara.maria.belen@live.com.ar"
          ],
          "phone": [],
          "homepage": [],
          "organization": "Centro de Ecología Aplicada del Litoral (CECOAL-CONICET-UNNE).",
          "address": [
            "Ruta Provincial 5, km 2.5"
          ],
          "city": "Corrientes",
          "province": "Corrientes",
          "country": "AR",
          "postalCode": "3400",
          "createdBy": "crawler.gbif.org",
          "modifiedBy": "crawler.gbif.org",
          "created": "2024-05-13T01:43:45.478+00:00",
          "modified": "2024-05-13T01:43:45.478+00:00"
        },
        {
          "key": 5322543,
          "type": "CONTENT_PROVIDER",
          "primary": false,
          "userId": [],
          "firstName": "Matilde Silvia",
          "lastName": "Beresi",
          "position": [
            "investigadora"
          ],
          "email": [
            "mberesi@mendoza-conicet.gob.ar"
          ],
          "phone": [],
          "homepage": [],
          "organization": "IANIGLA-CCT CONICET Mendoza",
          "address": [
            "Av. Ruiz Leal s/n"
          ],
          "city": "Mendoza",
          "province": "Mendoza",
          "country": "AR",
          "postalCode": "5500",
          "createdBy": "crawler.gbif.org",
          "modifiedBy": "crawler.gbif.org",
          "created": "2024-05-13T01:43:45.479+00:00",
          "modified": "2024-05-13T01:43:45.479+00:00"
        },
        {
          "key": 5322544,
          "type": "ADMINISTRATIVE_POINT_OF_CONTACT",
          "primary": true,
          "userId": [
            "https://orcid.org/0000-0002-4716-1309"
          ],
          "firstName": "Susana Mariel",
          "lastName": "Devincenzi",
          "position": [
            "Curadora Colección"
          ],
          "email": [
            "sdevincenzi@mendoza-conicet.gob.ar"
          ],
          "phone": [
            "+54-261-5244274"
          ],
          "homepage": [
            "https://www.conicet.gov.ar/new_scp/detalle.php?id=40411&datos_academicos=yes&keywords="
          ],
          "organization": "IANIGLA-CCT CONICET Mendoza",
          "address": [
            "Av. Ruiz Leal s/n"
          ],
          "city": "Mendoza",
          "province": "Mendoza",
          "country": "AR",
          "postalCode": "5500",
          "createdBy": "crawler.gbif.org",
          "modifiedBy": "crawler.gbif.org",
          "created": "2024-05-13T01:43:45.480+00:00",
